version: "3.8"
services:
  httpstate:
    image: ghcr.io/aaronpowell/httpstatus:058d5b93178cb9f11d9aeb9405e07ef5875331c8
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
  mysql:
    image: mysql:8.0.31-debian
    volumes:
      - type: volume
        source: mysql-data
        target: /var/lib/mysql
      - type: bind
        source: ./mysql/init
        target: /docker-entrypoint-initdb.d
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
        mode: host
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: graal
      MYSQL_USER: user
      MYSQL_PASSWORD: pass

volumes:
  mysql-data:
    name: mysql-volume