name: Package

on:
  workflow_dispatch:
    inputs:
      release-name:
        description: 'アップロード先のRelease名'
        required: true

jobs:
  package:
    name: Create packages
    runs-on: ubuntu-18.04

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: packaging
        run: ./mvnw package
        working-directory: build-war

      - name: get tag id
        id: release-page
        run: echo "::set-output name=id::$(.github/scripts/build-war/find-release-page.bash ${{ secrets.GITHUB_TOKEN }} ${{ github.event.inputs.release-name }})"

      - name: upload
        run: .github/scripts/build-war/upload-modules.bash ${{ secrets.GITHUB_TOKEN }} ${{ steps.release-page.outputs.id }}
